/**
 * Rótulos padrão de headers do protocolo Habblet (cliente Nitro, release PRODUCTION-202101271337).
 * Chave: "in:123" / "out:456". Preenchido a partir da captura real documentada em docs/PROTOCOLO.md.
 *
 * Sufixos: "?" = leitura provável, ainda não confirmada pelo corpo do pacote.
 * Rótulos definidos pelo usuário na aba Protocolo têm prioridade sobre estes.
 */
export const KNOWN_HEADERS: Record<string, string> = {
  // ---- saída (cliente → servidor) ----
  'out:4096': 'Hello / versão do cliente',
  'out:2490': 'Machine id',
  'out:2419': 'SSO ticket (sensível)',
  'out:2596': 'Pong',
  'out:249': 'Navegador: buscar',
  'out:2230': 'Quarto: pedir dados (roomId, 1, 0)',
  'out:2312': 'Quarto: entrar (roomId, senha)',
  'out:3157': 'Pedido de amizade (nome)',
  'out:137': 'Aceitar pedido(s) de amizade (count, ids)',
  'out:3301': 'Olhar para (x, y)',
  'out:3320': 'Andar até (x, y)',
  'out:3997': 'Seguir amigo (userId)',
  'out:2991': 'Quarto: pedir info (roomId, flag) ?',
  'out:431': 'Usuário: tags (roomIndex)',
  'out:2091': 'Usuário: emblemas (userId)',
  'out:2138': 'Usuário: relacionamentos (userId)',
  'out:1314': 'Falar na sala (texto, estilo)',
  'out:1543': 'Sussurrar ("nome texto", estilo)',
  'out:1597': 'Comecei a digitar',
  'out:1474': 'Parei de digitar',
  'out:3567': 'Console: enviar mensagem (userId, texto)',
  'out:3878': 'Perfil pelo nome ?',
  'out:875': 'Planta: salvar (mapa, porta, espessuras)',
  'out:1258': 'Mobi: colocar do inventário ("id x y dir" ou "id :w=…")',
  'out:248': 'Mobi de chão: mover/girar (id, x, y, dir)',
  'out:99': 'Mobi de chão: usar (id, 0)',
  'out:3456': 'Mobi de chão: pegar (10, id)',
  'out:168': 'Mobi de parede: mover (id, posição)',
  'out:210': 'Mobi de parede: usar (id, 0)',
  'out:711': 'Pintura: aplicar item do inventário (id)',
  'out:3150': 'Inventário: pedir lista',
  'out:1195': 'Catálogo: pedir índice',
  'out:412': 'Catálogo: pedir página (pageId, -1, modo)',
  'out:3492': 'Catálogo: COMPRAR (pageId, ofertaId, extra, qtd)',
  'out:1990': 'Dado: jogar (id)',
  'out:2281': 'Mobi: gravar texto (id, …)',
  'out:357': 'Info do usuário ?',
  'out:273': 'Moedas ?',

  // ---- entrada (servidor → cliente) ----
  'in:3928': 'Ping',
  'in:374': 'Sala: usuários (id, nome, missão, figura, pos)',
  'in:1640': 'Sala: status/movimento dos avatares',
  'in:2661': 'Sala: usuário saiu (roomIndex)',
  'in:1717': 'Sala: digitando',
  'in:1167': 'Sala: efeito do avatar',
  'in:1797': 'Sala: ocioso',
  'in:1631': 'Sala: expressão ?',
  'in:2233': 'Sala: dança ?',
  'in:1474': 'Sala: item na mão ?',
  'in:1446': 'Chat da sala',
  'in:3920': 'Sala: info/visual do usuário',
  'in:2182': 'Habblet: nome colorido / tag',
  'in:1087': 'Usuário: emblemas',
  'in:2016': 'Usuário: relacionamentos',
  'in:2219': 'Amizade: pedido recebido',
  'in:2800': 'Amigos: atualização (novo amigo / status)',
  'in:3130': 'Amigos: lista completa',
  'in:2725': 'Eu: id, nome, figura',
  'in:1036': 'Grito na sala',
  'in:2704': 'Sussurro recebido',
  'in:1587': 'Console: mensagem recebida (senderId, texto, segundos)',
  'in:286': 'Diálogo/aviso do servidor',
  'in:432': 'Habblet: comandos de chat disponíveis',
  'in:2586': 'Permissões de chat',
  'in:758': 'Quarto: pronto',
  'in:160': 'Quarto: encaminhado para (roomId)',
  'in:339': 'Quarto: você é o dono',
  'in:1702': 'Quarto: info/configurações (nome, descrição) ?',
  'in:122': 'Saiu do quarto (visão do hotel)',
  'in:1778': 'Quarto: mobis de chão (id, tipo, x, y, direção, z)',
  'in:1534': 'Quarto: mobi de chão colocado',
  'in:2703': 'Quarto: mobi de chão removido (id)',
  'in:3776': 'Quarto: mobi de chão movido/atualizado',
  'in:1369': 'Quarto: mobis de parede (id, tipo, posição, estado)',
  'in:687': 'Quarto: dados (nome, descrição)',
  'in:2753': 'Quarto: altura do topo de cada casa (piso + mobis)',
  'in:1301': 'Quarto: planta (x = sem chão, dígito = altura do piso)',
  'in:3990': 'Quarto: casas ocupadas por mobi (resposta ao 1687)',
  'in:1664': 'Quarto: casa da porta (x, y, direção)',
  'out:3559': 'Quarto: pedir a casa da porta (:floor)',
  'out:1687': 'Quarto: pedir as casas ocupadas (:floor)',
  'in:3052': 'Navegador: abas',
  'in:1562': 'Navegador: categorias',
  'in:3984': 'Navegador: salas em destaque',
  'in:3244': 'Navegador: promovidas',
  'in:806': 'Conquistas: lista',
  'in:325': 'Denúncia: categorias',
  'in:222': 'Game center',
  'in:2107': 'Conquista progrediu',
  'in:2454': 'Quarto: pintura',
  'in:2031': 'Quarto: modelo',
  'in:2690': 'Navegador: resultados',
  'in:1112': 'Habblet: rádio / player',
  'in:2187': 'Quarto: mobi de parede colocado',
  'in:2009': 'Quarto: mobi de parede atualizado',
  'in:2547': 'Mobi de chão: estado mudou (id, dados)',
  'in:3801': 'Aviso do servidor (janela)',
  'in:1032': 'Catálogo: índice (páginas e ofertas)',
  'in:804': 'Catálogo: página (ofertas, preços, produtos)',
  'in:869': 'Catálogo: compra aceita',
  'in:2103': 'Inventário: itens novos (ids)',
  'in:994': 'Inventário: lista de mobis (fragmento)',
  'in:159': 'Inventário: item saiu (colocado no quarto)',
  'in:1992': 'Notificação (imagem/texto)',
  'in:3870': 'Console: convite de quarto (userId, texto)',
  'in:1453': 'Mobis: dados atualizados ?',
  'in:416': 'Mobi: placar/ranking ?',
  'in:360': 'Mobi de chão: movimento ?',
};
